# Generated by Django 4.2.3 on 2023-07-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0003_chamada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chamada',
        ),
    ]
