# Generated by Django 4.2.3 on 2023-07-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0004_delete_chamada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inicio_chamada', models.DateTimeField()),
                ('duracao', models.DurationField()),
                ('agentes', models.CharField(max_length=100)),
                ('interlocutores', models.CharField(max_length=100)),
                ('servico', models.CharField(max_length=100)),
                ('habilidades', models.CharField(max_length=100)),
                ('id_chamada', models.CharField(max_length=100)),
                ('arquivoTXT', models.CharField(max_length=255)),
                ('arquivoF', models.FileField(upload_to='chamadas/', verbose_name='Arquivo')),
            ],
        ),
    ]
