# Generated by Django 4.2.3 on 2023-07-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0006_delete_chamada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interlocutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_chamada', models.DateTimeField()),
                ('duracao', models.DurationField()),
                ('servico', models.CharField(max_length=100)),
                ('habilidades', models.CharField(max_length=100)),
                ('id_chamada', models.CharField(max_length=100)),
                ('arquivo', models.CharField(max_length=100)),
                ('agentes', models.ManyToManyField(related_name='chamadas', to='a1.agente')),
                ('interlocutores', models.ManyToManyField(related_name='chamadas', to='a1.interlocutor')),
            ],
        ),
    ]
